In [5]:
import numpy as np 
import pandas as  pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings 
warnings.filterwarnings("ignore")

In [6]:
df=pd.read_csv("heart.csv")

In [7]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

EDA

In [8]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='str')

In [9]:
df.shape

(880, 12)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 880 entries, 0 to 879
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             880 non-null    int64
 1   Sex             880 non-null    str
 2   ChestPainType   880 non-null    str
 3   RestingBP       880 non-null    int64
 4   Cholesterol     880 non-null    int64
 5   FastingBS       880 non-null    int64
 6   RestingECG      880 non-null    str
 7   MaxHR           880 non-null    int64
 8   ExerciseAngina  880 non-null    str
 9   Oldpeak         880 non-null    float64
 10  ST_Slope        880 non-null    str
 11  HeartDisease    880 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 82.6 KB

In [11]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,880.000000,880.000000,880.000000,880.000000,880.000000,880.000000,880.000000
mean,53.464773,132.237500,197.640909,0.236364,136.282955,0.885682,0.554545
std,9.474888,18.600811,111.164027,0.425090,25.519328,1.059772,0.497299
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,170.750000,0.000000,119.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,137.000000,0.600000,1.000000
75%,60.000000,140.000000,268.000000,0.000000,155.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000